<?php
/*
 *  Copyright (C) 2012 MyProfile Project
 *  
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal 
 *  in the Software without restriction, including without limitation the rights 
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
 *  copies of the Software, and to permit persons to whom the Software is furnished 
 *  to do so, subject to the following conditions:

 *  The above copyright notice and this permission notice shall be included in all 
 *  copies or substantial portions of the Software.

 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 *  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 *  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 *  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
 *  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 *  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

ini_set('memory_limit', '64M');
set_time_limit ( 0 );

define('INCLUDE_CHECK',true);

$ret = '';
// Create database tables and write configuration to disk
if (isset($_REQUEST['submit'])) {

    // create conf dir if it doesn't exist
    if (!is_dir('../conf/')) {
        if (!mkdir('../conf/', 0775))
            die('Failed to create conf/ dir...');
        $conf_status = "<p><font color=\"green\"><strong>Success!</strong></font> Configuration dir has been created.</p>\n";
    } else {
        $conf_status = "<p><strong>Skipped.</strong> Configuration dir already exists.</p>\n";
    }

    // write configuration to config.php
    $cf = fopen('../conf/config.php', 'w') or die('Cannot create the config.php file!');

    $content = "<?php\n";
    $content .= "// ------------- AUTOGENERATED FILE ---------------- //\n";
    $content .= "\n";
    $content .= "/* Version */\n";
    $content .= 'define (\'VERSION\', \'0.0.1\');' . "\n";
    $content .= "\n";
    $content .= "/* Cache time to live - default 48h */\n";
    $content .= 'define (\'CACHE_TTL\', \'' . 48 * 60 * 60 . '\');' . "\n";
    $content .= "\n";
    $content .= "/* SPARQL endpoint */\n";
    $content .= 'define (\'SPARQL_ENDPOINT\', \'' . trim($_REQUEST['endpoint']) . '\');' . "\n";
    $content .= "\n";
    $content .= "?>";

    fwrite($cf, $content);
    fclose($cf);
    $cf_status = "<p><font color=\"green\"><strong>Success!</strong></font> Configuration file has been saved to disk.</p>\n";
    
    // create cache dir if it doesn't exist
    if (!is_dir('cache/')) {
        if (!mkdir('cache/', 0775))
            die('Failed to create cache/ dir...');
        $cache_status = "<p><font color=\"green\"><strong>Success!</strong></font> Cache dir has been created.</p>\n";
    } else {
        $cache_status = "<p><strong>Skipped.</strong> Cache dir already exists.</p>\n";
    }
    
    // create logs dir if it doesn't exist
    if (!is_dir('logs/')) {
        if (!mkdir('logs/', 0775))
            die('Failed to create logs/ dir...');
        $logs_status = "<p><font color=\"green\"><strong>Success!</strong></font> Logs dir has been created.</p>\n";
    } else {
        $logs_status = "<p><strong>Skipped.</strong> Logs dir already exists.</p>\n";
    }
    
    // create dir where we store profiles if it doesn't exist
    if (!is_dir('people/')) {
        if (!mkdir('people/', 0775))
            die('Failed to create people/ dir...');
        $people_status = "<p><font color=\"green\"><strong>Success!</strong></font> Profile root dir has been created.</p>\n";
    } else {
        $people_status = "<p><strong>Skipped.</strong> Profile root dir already exists.</p>\n";
    }

    // display success
    $ret .= "<p><font align=\"left\" style=\"font-size: 2em; text-shadow: 0 1px 1px #cccccc;\">MyProfile LDP Installation</font></p>\n";
    $ret .= 'Your installation is complete!';
    $ret .= "<br/><div>\n";
    $ret .= $conf_status;
    $ret .= $cf_status;
    $ret .= $cache_status;
    $ret .= $logs_status;
    $ret .= $people_status;
    $ret .= "<br/><p><a href=\"/index\">Take me to the main page!</a></p>\n";
    $ret .= "</form></div>\n";
} else {
    // display form        
    $ret .= "<div style=\"width: 600px;\">\n";
    $ret .= "<p><font align=\"left\" style=\"font-size: 2em; text-shadow: 0 1px 1px #cccccc;\">MyProfile LDP Installation</font></p>\n";
    
    $ret .= "<form action=\"\" method=\"POST\">\n";
    $ret .= "<p>For security reasons, once the installation is complete, you should remove this file (<strong>/public/install.php</strong>).</p>\n";
    
    $ret .= "<table>\n";
    $ret .= "<tr><td>SPARQL endpoint address: </td><td><input type=\"text\" name=\"endpoint\" size=\"40\" value=\"http://localhost:8890/sparql\"></td></tr>\n";

    $ret .= "<tr><td colspan=\"2\"><p><input class=\"btn btn-primary\" type=\"submit\" name=\"submit\" value=\" Install \"></p></td></tr>\n";
    $ret .= "</table>\n";
    $ret .= "</form></div>\n";
}

echo $ret;
include 'footer.php';

?>
